// Code generated by sqlc. DO NOT EDIT.
// source: answer.sql

package db

import (
	"context"
	"database/sql"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answer (
    id,
    quiz_id,
    owner,
    content,
    hash_content,
    timestamp_created,
    status
) values (
 $1, $2, $3, $4, $5, $6, $7
) RETURNING id, quiz_id, owner, content, hash_content, timestamp_created, status, created_at
`

type CreateAnswerParams struct {
	ID               string         `json:"id"`
	QuizID           string         `json:"quiz_id"`
	Owner            string         `json:"owner"`
	Content          sql.NullString `json:"content"`
	HashContent      string         `json:"hash_content"`
	TimestampCreated int64          `json:"timestamp_created"`
	Status           int32          `json:"status"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRowContext(ctx, createAnswer,
		arg.ID,
		arg.QuizID,
		arg.Owner,
		arg.Content,
		arg.HashContent,
		arg.TimestampCreated,
		arg.Status,
	)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Owner,
		&i.Content,
		&i.HashContent,
		&i.TimestampCreated,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnswer = `-- name: DeleteAnswer :exec
DELETE FROM answer WHERE ID = $1
`

func (q *Queries) DeleteAnswer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAnswer, id)
	return err
}

const findAnswerById = `-- name: FindAnswerById :one
SELECT id, quiz_id, owner, content, hash_content, timestamp_created, status, created_at FROM answer WHERE id = $1 LIMIT 1
`

func (q *Queries) FindAnswerById(ctx context.Context, id string) (Answer, error) {
	row := q.db.QueryRowContext(ctx, findAnswerById, id)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Owner,
		&i.Content,
		&i.HashContent,
		&i.TimestampCreated,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
