// Code generated by sqlc. DO NOT EDIT.
// source: chain_config.sql

package db

import (
	"context"
)

const getChainConfig = `-- name: GetChainConfig :one
SELECT id, chain_id, contract_address, rpc_url, wss_url, block_number, step_number, created_at, updated_at FROM chain_config
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChainConfig(ctx context.Context, id int32) (ChainConfig, error) {
	row := q.db.QueryRowContext(ctx, getChainConfig, id)
	var i ChainConfig
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.ContractAddress,
		&i.RpcUrl,
		&i.WssUrl,
		&i.BlockNumber,
		&i.StepNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBlockNumber = `-- name: UpdateBlockNumber :exec
UPDATE chain_config
SET block_number = $2
WHERE id = $1
`

type UpdateBlockNumberParams struct {
	ID          int32 `json:"id"`
	BlockNumber int64 `json:"block_number"`
}

func (q *Queries) UpdateBlockNumber(ctx context.Context, arg UpdateBlockNumberParams) error {
	_, err := q.db.ExecContext(ctx, updateBlockNumber, arg.ID, arg.BlockNumber)
	return err
}
