// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Answer struct {
	ID          string         `json:"id"`
	QuizID      sql.NullString `json:"quiz_id"`
	Owner       string         `json:"owner"`
	Content     string         `json:"content"`
	HashContent string         `json:"hash_content"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Quiz struct {
	ID          string         `json:"id"`
	Owner       string         `json:"owner"`
	Content     sql.NullString `json:"content"`
	HashContent string         `json:"hash_content"`
	Answer      sql.NullString `json:"answer"`
	HashAnswer  sql.NullString `json:"hash_answer"`
	Duration    int32          `json:"duration"`
	Status      int32          `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
