// Code generated by sqlc. DO NOT EDIT.
// source: quiz.sql

package db

import (
	"context"
	"database/sql"
)

const countQuiz = `-- name: CountQuiz :one
SELECT count(*) FROM quiz
`

func (q *Queries) CountQuiz(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuiz)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuizByStatus = `-- name: CountQuizByStatus :one
SELECT count(*) FROM quiz WHERE status = $1
`

func (q *Queries) CountQuizByStatus(ctx context.Context, status int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuizByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quiz (
    id,
    owner,
    content,
    hash_content,
    answer,
    hash_answer,
    timestamp_created,
    status
) values (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, owner, content, hash_content, answer, hash_answer, timestamp_created, status, created_at
`

type CreateQuizParams struct {
	ID               string         `json:"id"`
	Owner            string         `json:"owner"`
	Content          sql.NullString `json:"content"`
	HashContent      string         `json:"hash_content"`
	Answer           sql.NullString `json:"answer"`
	HashAnswer       sql.NullString `json:"hash_answer"`
	TimestampCreated int64          `json:"timestamp_created"`
	Status           int32          `json:"status"`
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, createQuiz,
		arg.ID,
		arg.Owner,
		arg.Content,
		arg.HashContent,
		arg.Answer,
		arg.HashAnswer,
		arg.TimestampCreated,
		arg.Status,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Content,
		&i.HashContent,
		&i.Answer,
		&i.HashAnswer,
		&i.TimestampCreated,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quiz WHERE ID = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteQuiz, id)
	return err
}

const findQuizById = `-- name: FindQuizById :one
SELECT id, owner, content, hash_content, answer, hash_answer, timestamp_created, status, created_at FROM quiz WHERE id = $1 LIMIT 1
`

func (q *Queries) FindQuizById(ctx context.Context, id string) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, findQuizById, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Content,
		&i.HashContent,
		&i.Answer,
		&i.HashAnswer,
		&i.TimestampCreated,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const findQuizByStatus = `-- name: FindQuizByStatus :many
SELECT id, owner, content, hash_content, answer, hash_answer, timestamp_created, status, created_at FROM quiz WHERE status = $1 ORDER BY created_at DESC LIMIT $3 OFFSET $2
`

type FindQuizByStatusParams struct {
	Status int32 `json:"status"`
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) FindQuizByStatus(ctx context.Context, arg FindQuizByStatusParams) ([]Quiz, error) {
	rows, err := q.db.QueryContext(ctx, findQuizByStatus, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Content,
			&i.HashContent,
			&i.Answer,
			&i.HashAnswer,
			&i.TimestampCreated,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishQuiz = `-- name: FinishQuiz :one
UPDATE quiz SET status = 0 WHERE id = $1 AND status = 1 RETURNING id, owner, content, hash_content, answer, hash_answer, timestamp_created, status, created_at
`

func (q *Queries) FinishQuiz(ctx context.Context, id string) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, finishQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Content,
		&i.HashContent,
		&i.Answer,
		&i.HashAnswer,
		&i.TimestampCreated,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateQuizAnswer = `-- name: UpdateQuizAnswer :one
UPDATE quiz SET answer = $2 where id = $1 RETURNING id, owner, content, hash_content, answer, hash_answer, timestamp_created, status, created_at
`

type UpdateQuizAnswerParams struct {
	ID     string         `json:"id"`
	Answer sql.NullString `json:"answer"`
}

func (q *Queries) UpdateQuizAnswer(ctx context.Context, arg UpdateQuizAnswerParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, updateQuizAnswer, arg.ID, arg.Answer)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Content,
		&i.HashContent,
		&i.Answer,
		&i.HashAnswer,
		&i.TimestampCreated,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateQuizContent = `-- name: UpdateQuizContent :one
UPDATE quiz SET content = $2 WHERE id = $1 RETURNING id, owner, content, hash_content, answer, hash_answer, timestamp_created, status, created_at
`

type UpdateQuizContentParams struct {
	ID      string         `json:"id"`
	Content sql.NullString `json:"content"`
}

func (q *Queries) UpdateQuizContent(ctx context.Context, arg UpdateQuizContentParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, updateQuizContent, arg.ID, arg.Content)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Content,
		&i.HashContent,
		&i.Answer,
		&i.HashAnswer,
		&i.TimestampCreated,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
